version: '1.0'
stages:
  - prepare
  - build
  - test
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: prepare
  my_python_docker_image:
    title: Building Docker Image
    type: build
    stage: build
    image_name: my-flask-image
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: Dockerfile
  my_unit_tests:
    title: Running Unit tests
    stage: test
    image: '${{my_python_docker_image}}'
    commands:
      - pip install pytest
      - pytest
